In [320]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [321]:
# Importing the dataset
dataset = pd.read_csv('odataset.csv')


In [322]:
print(dataset)

    year  month  day  offset  meat  bread  onion  eggs  milk
0   2019      8   24       1     1      0      0     0     0
1   2019      8   25       2     1      1      1     1     1
2   2019      8   26       3     0      0      0     0     0
3   2019      8   27       4     0      1      0     0     0
4   2019      8   28       5     0      0      0     0     0
..   ...    ...  ...     ...   ...    ...    ...   ...   ...
94  2019     11   26      95     0      0      0     0     0
95  2019     11   27      96     0      0      0     0     0
96  2019     11   28      97     0      0      0     0     0
97  2019     11   29      98     0      0      0     0     0
98  2019     11   30      99     0      0      0     0     0

[99 rows x 9 columns]


In [323]:
eggs = dataset[["eggs"]].values
milks = dataset[["milk"]].values
bread = dataset[["bread"]].values
onions   = dataset[["onion"]].values
meat = dataset[["meat"]].values


In [324]:
w = []
countW = 0


In [325]:
for egg in eggs:
    
    countW = countW+1
    w.append(countW)
    if egg != 0:
        countW = 0
dataset["eggs_w"] = w
        
w = []
countW = 0

for milk in milks:
    
    countW = countW+1
    w.append(countW)
    if milk != 0:
        countW = 0

dataset["milk_w"] = w        

w = []
countW = 0
        
for b in bread:
    
    countW = countW+1
    w.append(countW)
    if b != 0:
        countW =0

dataset["bread_w"] = w

w = []
countW = 0
        
for onion in onions:
    
    countW = countW+1
    w.append(countW)
    if onion != 0:
        countW = 0
dataset["onion_w"] = w

w = []
countW = 0
        
for m in meat:
    
    countW = countW+1
    w.append(countW)
    if m != 0:
        countW =0
        
dataset["meat_w"] = w
    

In [326]:
print(len(dataset))

99


In [327]:
emptyIndex = []
index = 0
for row in dataset.iloc[:, 4:9].values:
    if all(r == 0 for r in row):
        emptyIndex.append(index)
    index = index + 1

In [328]:
dd = dataset.drop(emptyIndex, axis = 0)

In [329]:
print(len(dd))
print(dd)

31
    year  month  day  offset  meat  bread  onion  eggs  milk  eggs_w  milk_w  \
0   2019      8   24       1     1      0      0     0     0       1       1   
1   2019      8   25       2     1      1      1     1     1       2       2   
3   2019      8   27       4     0      1      0     0     0       2       2   
5   2019      8   29       6     1      1      1     1     1       4       4   
8   2019      9    1       9     1      1      0     0     0       3       3   
11  2019      9    4      12     0      1      0     1     1       6       6   
13  2019      9    6      14     0      1      0     1     0       2       2   
21  2019      9   14      22     0      0      0     1     1       8      10   
22  2019      9   15      23     1      1      1     0     0       1       1   
27  2019      9   20      28     0      1      1     1     1       6       6   
31  2019      9   24      32     0      1      1     1     1       4       4   
35  2019      9   28      36     0   

In [330]:
y_train = dataset[["milk"]]
X_train = dataset[["milk_w"]]


X_test = np.arange( (X_train.iloc[-1:,-1].values + 1), X_train.iloc[-1:,-1].values + 7, 1)
X_test = X_test.reshape(-1,1)

mean = np.mean(X_train)
print(mean)

milk_w    3.555556
dtype: float64


In [331]:
print(mean)
print(X_test)

milk_w    3.555556
dtype: float64
[[ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [332]:
# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)
    
# Predicting the Test set results
y_pred = classifier.predict(X_test)



C:\Users\yrtie\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\yrtie\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [333]:
print(X_test)
print(y_pred)


[[ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
[0 0 0 1 1 1]


In [334]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
print(X_test.reshape(1,-1))
print(y_pred)

[[ 7  8  9 10 11 12]]
[0 0 0 1 1 1]


In [335]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)
    
# Predicting the Test set results
y_pred = classifier.predict(X_test)
print(y_pred)
print(X_test)


[0 1 1 1 1 1]
[[ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


C:\Users\yrtie\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [336]:
# Fitting Decision Tree Classification to the Training set
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy')
classifier.fit(X_train, y_train)
    
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [337]:
print(X_test)
print(y_pred)

[[ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
[0 0 0 1 1 1]


In [339]:
import keras
from keras.models import Sequential
from keras.layers import Dense

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Initialising the ANN
classifier = Sequential()
    
# Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim = 2, init = 'uniform', activation = 'sigmoid', input_dim = 1))

classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))
    
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

# Part 3 - Making the predictions and evaluating the model
# Predicting the Test set results
y_pred = classifier.predict(X_test)


C:\Users\yrtie\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:13: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", input_dim=1, units=2, kernel_initializer="uniform")`
  del sys.path[0]
C:\Users\yrtie\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:15: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=1, kernel_initializer="uniform")`
  from ipykernel import kernelapp as app
C:\Users\yrtie\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:18: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
C:\Users\yrtie\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:24: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.


Epoch 1/100
99/99 [==============================] - 0s 2ms/step - loss: 0.6919 - accuracy: 0.7374
Epoch 2/100
99/99 [==============================] - 0s 101us/step - loss: 0.6889 - accuracy: 0.8182
Epoch 3/100
99/99 [==============================] - 0s 158us/step - loss: 0.6859 - accuracy: 0.8182
Epoch 4/100
99/99 [==============================] - 0s 157us/step - loss: 0.6831 - accuracy: 0.8182
Epoch 5/100
99/99 [==============================] - 0s 158us/step - loss: 0.6803 - accuracy: 0.8182
Epoch 6/100
99/99 [==============================] - 0s 158us/step - loss: 0.6773 - accuracy: 0.8182
Epoch 7/100
99/99 [==============================] - 0s 158us/step - loss: 0.6747 - accuracy: 0.8182
Epoch 8/100
99/99 [==============================] - 0s 66us/step - loss: 0.6717 - accuracy: 0.8182
Epoch 9/100
99/99 [==============================] - 0s 157us/step - loss: 0.6692 - accuracy: 0.8182
Epoch 10/100
99/99 [==============================] - 0s 158us/step - loss: 0.6665 - accuracy:

99/99 [==============================] - 0s 158us/step - loss: 0.5410 - accuracy: 0.8182
Epoch 82/100
99/99 [==============================] - 0s 158us/step - loss: 0.5401 - accuracy: 0.8182
Epoch 83/100
99/99 [==============================] - 0s 158us/step - loss: 0.5391 - accuracy: 0.8182
Epoch 84/100
99/99 [==============================] - 0s 158us/step - loss: 0.5380 - accuracy: 0.8182
Epoch 85/100
99/99 [==============================] - 0s 157us/step - loss: 0.5369 - accuracy: 0.8182
Epoch 86/100
99/99 [==============================] - 0s 0us/step - loss: 0.5361 - accuracy: 0.8182
Epoch 87/100
99/99 [==============================] - 0s 66us/step - loss: 0.5350 - accuracy: 0.8182
Epoch 88/100
99/99 [==============================] - 0s 158us/step - loss: 0.5340 - accuracy: 0.8182
Epoch 89/100
99/99 [==============================] - 0s 158us/step - loss: 0.5330 - accuracy: 0.8182
Epoch 90/100
99/99 [==============================] - 0s 158us/step - loss: 0.5322 - accuracy: 0.8

In [ ]:
print(y_pred)